version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
    ports:
      - "4000:4000"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8000:8000"  # Change port mapping from 8000 to 5000
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+mysqldb://fastapi_user:fastapi_password@db/fastapi_db"

volumes:
  mysql_data:
