version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db:3306/mydatabase"
    depends_on:
      - db

  db:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
